name: tweetdelete
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - blinker=1.4
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.6.1
  - idna=2.8
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - oauthlib=3.0.1
  - openssl=1.1.1b
  - pip=19.1
  - pycparser=2.19
  - pyjwt=1.7.1
  - pymysql=0.9.3
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.8.0
  - readline=7.0
  - requests=2.21.0
  - requests-oauthlib=1.2.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - twython=3.7.0
  - urllib3=1.24.2
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11

